### ISSUE TITLE
按需加载你实现了吗？

### ISSUE THREAD

**Issue by wuzhoubo** [RexkentZheng/test-nuxt#1]
你好，我这边同样遇到iview按需加载的问题，你解决了吗？

**Comment by RexkentZheng** [comment]
目前还是没有，改成全部加载了，问题我公司的大腿，大腿说就首页加载慢些，其他的没啥影响

**Comment by wuzhoubo** [comment]
我们公司的大腿也是这么说的，就算按需加载作用也不大
